name: 🪅 Release

on:
    push:
        branches: ['master']

jobs:
    code-quality:
        name: 'Code Quality'
        uses: equinor/sparql-graph/.github/workflows/code-quality.yml@master
        secrets:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    bump-version:
        name: '🦆 Bump version'
        needs: [code-quality]
        runs-on: ubuntu-latest
        environment: BUMP
        permissions: write-all

        steps:
            - name: 'Checkout source code'
              uses: 'actions/checkout@v3'
              with:
                  ref: ${{ github.ref }}
            - name: 'cat package.json'
              run: cat ./package.json
            - name: 'Automated Version Bump'
              id: version-bump
              uses: 'phips28/gh-action-bump-version@v9.0.16'
              with:
                  patch-wording: 'patch: ,fixes: ,fix: ,chore: '
                  minor-wording: 'feat: '
                  major-wording: 'major: '
                  commit-message: 'CI: bumps version to {{version}} [skip ci]'
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    build:
        needs: [bump-version]
        runs-on: ubuntu-latest
        name: '🤹‍♀️ Build'
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org
            - run: npm install --frozen-lockfile
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    publish:
        needs: build
        name: '📦 Publish'
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org
                  scope: '@equinor'
            - run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
            - run: npm publish --access=public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
