name: 🐩 Snyk Test & Monitor

on:
  schedule:
    # At 06:00 on every 3rd day
    - cron: "0 6 */3 * *"
  workflow_dispatch:

jobs:
  test-and-monitor:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PNPM & Install dependencies
        uses: ./.github/actions/setup-pnpm

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Authenticate
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Update snapshots at Snyk.io
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: pnpm nx run-many --target=snyk-monitor --output-style=stream

      - name: Snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
        run: pnpm nx run-many --target=snyk-test --configuration=production --output-style=stream
