name: Validate pull request

on:
    pull_request:
    workflow_dispatch:

jobs:
    validate:
        name: 'Validate pull request'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://npm.pkg.github.com/
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

            - name: Install project dependencies
              run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

            - name: Run tests
              run: npm run test -- --passWithNoTests

            - name: Check code quality
              run: npm run checkcode

            - name: Build library
              run: npm run build:lib
