name: Snyk
on: push
jobs:
    security:
        name: 'Snyk'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://npm.pkg.github.com/

            - name: Install project dependencies
              run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

            - uses: actions/checkout@master
            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/node@master
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  args: --sarif-file-output=snyk.sarif
            - name: Snyk version
              run: echo "${{ steps.snyk.outputs.version }}"
            - name: Snyk monitor
              run: snyk monitor
            - name: Upload result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v1
              with:
                  sarif_file: snyk.sarif
